#!/bin/bash

. eqi_utils.sh

# Source the site-specific configuration file
if [[ -f $EQI_CONFIG ]]
then
  echo "Sourcing configuration file: $EQI_CONFIG"
  . $EQI_CONFIG
fi

run="$1"

eqi_resume_init "$run" "encode_execute"
(( $? == $RET_COMPLETED )) && exit 0

enc_args=${@:1:1}
exec_args=${@:1}

echo ${enc_args}
echo ${exec_args}

python3 -m eqi.external_encoder ${enc_args}
easyvvuq_execute ${exec_args}

eqi_resume_finish "$run" "encode_execute"
