#!/bin/bash

. eqi_utils.sh

# Source the site-specific configuration file
if [[ -f $EQI_CONFIG ]]
then
  echo "Sourcing configuration file: $EQI_CONFIG"
  . $EQI_CONFIG
fi

run="$1"

eqi_resume_init "$run" "encode"
(( $? == $RET_COMPLETED )) && exit 0

python3 -m eqi.external_encoder $@

eqi_resume_finish "$run" "encode"
