#!/bin/bash

# Source the site-specific configuration file
if [[ -f $EASYPJ_CONFIG ]] 
then
  echo "Sourcing configuration file: $EASYPJ_CONFIG"
  . $EASYPJ_CONFIG
fi

#python3 -m easypj.easyvvuq_encode $@
enc_args=${@:1:6}
exec_args=${@:7}

echo ${enc_args}
echo ${exec_args}

python3 -m easypj.external_encoder ${enc_args}
python3 -m easypj.easyvvuq_execute ${exec_args}
